### ISSUE TITLE
One Question about the algorithm 

### ISSUE THREAD

**Issue by 202030481266** [benarnav/bytephase#1]
Hello, thank you for a job well done. I have some questions to ask you. Your algorithm implementation looks complicated (I don't know C). Can you explain the algorithm in a nutshell? I was curious about this part, and I was interested in what is the worst case complexity of the algorithm? Is it better than the theoretical squared complexity? Or is it a constant level optimization?

**Comment by benarnav** [comment]
Hi, I assume you're talking about the training algorithm. I haven't worked out the time complexity, but I have a more detailed explanation of the algorithm in this post: https://benjaminarnav.com/posts/bytephase/
